#======================================================================================================================#
# 自定義參數
#======================================================================================================================#
solaris:
  #====================================================================================================================#
  # 自定義：Server Connection Configuration
  #====================================================================================================================#
  server:
    free5gc:
      http: 
        url: ${K8S_URL}
  prometheus:
    url: ${PROMETHEUS_URL}
    namespace: ${PROMETHEUS_NAMESPACE}
#======================================================================================================================#
# Spring
#======================================================================================================================#
spring: 
  #====================================================================================================================#
  # Data Source
  #====================================================================================================================#  
  datasource:    
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}