package oam.security.model.resource.example;

public class ExampleContextString {
	
	public static String CREATE_UE_JSON_STRING_FOR_WEB_COMMUNITY = "{\r\n"
			+ "  \"plmnID\": \"20893\",\r\n"
			+ "  \"ueId\": \"imsi-208930000000014\",\r\n"
			+ "  \"AuthenticationSubscription\": {\r\n"
			+ "    \"authenticationManagementField\": \"8000\",\r\n"
			+ "    \"authenticationMethod\": \"5G_AKA\",\r\n"
			+ "    \"milenage\": {\r\n"
			+ "      \"op\": {\r\n"
			+ "        \"encryptionAlgorithm\": 0,\r\n"
			+ "        \"encryptionKey\": 0,\r\n"
			+ "        \"opValue\": \"8e27b6af0e692e750f32667a3b14605d\"\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    \"opc\": {\r\n"
			+ "      \"encryptionAlgorithm\": 0,\r\n"
			+ "      \"encryptionKey\": 0,\r\n"
			+ "      \"opcValue\": \"\"\r\n"
			+ "    },\r\n"
			+ "    \"permanentKey\": {\r\n"
			+ "      \"encryptionAlgorithm\": 0,\r\n"
			+ "      \"encryptionKey\": 0,\r\n"
			+ "      \"permanentKeyValue\": \"8baf473f2f8fd09487cccbd7097c6862\"\r\n"
			+ "    },\r\n"
			+ "    \"sequenceNumber\": \"16f3b3f70fc2\"\r\n"
			+ "  },\r\n"
			+ "  \"AccessAndMobilitySubscriptionData\": {\r\n"
			+ "    \"gpsis\": [\r\n"
			+ "      \"msisdn-0900000000\"\r\n"
			+ "    ],\r\n"
			+ "    \"nssai\": {\r\n"
			+ "      \"defaultSingleNssais\": [\r\n"
			+ "        {\r\n"
			+ "          \"sst\": 1,\r\n"
			+ "          \"sd\": \"010203\",\r\n"
			+ "          \"isDefault\": true\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"singleNssais\": [\r\n"
			+ "\r\n"
			+ "      ]\r\n"
			+ "    },\r\n"
			+ "    \"subscribedUeAmbr\": {\r\n"
			+ "      \"downlink\": \"2 Gbps\",\r\n"
			+ "      \"uplink\": \"1 Gbps\"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"SessionManagementSubscriptionData\": [\r\n"
			+ "    {\r\n"
			+ "      \"singleNssai\": {\r\n"
			+ "        \"sst\": 1,\r\n"
			+ "        \"sd\": \"010203\"\r\n"
			+ "      },\r\n"
			+ "      \"dnnConfigurations\": {\r\n"
			+ "        \"internet\": {\r\n"
			+ "          \"sscModes\": {\r\n"
			+ "            \"defaultSscMode\": \"SSC_MODE_1\",\r\n"
			+ "            \"allowedSscModes\": [\r\n"
			+ "              \"SSC_MODE_2\",\r\n"
			+ "              \"SSC_MODE_3\"\r\n"
			+ "            ]\r\n"
			+ "          },\r\n"
			+ "          \"pduSessionTypes\": {\r\n"
			+ "            \"defaultSessionType\": \"IPV4\",\r\n"
			+ "            \"allowedSessionTypes\": [\r\n"
			+ "              \"IPV4\"\r\n"
			+ "            ]\r\n"
			+ "          },\r\n"
			+ "          \"sessionAmbr\": {\r\n"
			+ "            \"uplink\": \"200 Mbps\",\r\n"
			+ "            \"downlink\": \"100 Mbps\"\r\n"
			+ "          },\r\n"
			+ "          \"5gQosProfile\": {\r\n"
			+ "            \"5qi\": 9,\r\n"
			+ "            \"arp\": {\r\n"
			+ "              \"priorityLevel\": 8\r\n"
			+ "            },\r\n"
			+ "            \"priorityLevel\": 8\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  ],\r\n"
			+ "  \"SmfSelectionSubscriptionData\": {\r\n"
			+ "    \"subscribedSnssaiInfos\": {\r\n"
			+ "      \"01010203\": {\r\n"
			+ "        \"dnnInfos\": [\r\n"
			+ "          {\r\n"
			+ "            \"dnn\": \"internet\"\r\n"
			+ "          }\r\n"
			+ "        ]\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"AmPolicyData\": {\r\n"
			+ "    \"subscCats\": [\r\n"
			+ "      \"free5gc\"\r\n"
			+ "    ]\r\n"
			+ "  },\r\n"
			+ "  \"SmPolicyData\": {\r\n"
			+ "    \"smPolicySnssaiData\": {\r\n"
			+ "      \"01010203\": {\r\n"
			+ "        \"snssai\": {\r\n"
			+ "          \"sst\": 1,\r\n"
			+ "          \"sd\": \"010203\"\r\n"
			+ "        },\r\n"
			+ "        \"smPolicyDnnData\": {\r\n"
			+ "          \"internet\": {\r\n"
			+ "            \"dnn\": \"internet\"\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"FlowRules\": [\r\n"
			+ "\r\n"
			+ "  ]\r\n"
			+ "}";
	public static String CREATE_GNB_FOR_API = "{\r\n"
			+ "    \"mcc\": \"001\",\r\n"
			+ "    \"mnc\": \"35\",\r\n"
			+ "    \"slice\":{\r\n"
			+ "        \"sst\": 1,\r\n"
			+ "        \"sd\": \"010000\"\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static String CREATE_UE_FOR_API = "{\r\n"
			+ "    \"supi\": \"imsi-208930000000012\",\r\n"
			+ "    \"mcc\": \"001\",\r\n"
			+ "    \"mnc\": \"35\",\r\n"
			+ "    \"key\": \"00112233445566778899AABBCCDDEEFF\",\r\n"
			+ "    \"opCode\":\"FEDCBA9876543210FEDCBA9876543210\",\r\n"
			+ "    \"opType\": \"OP\",\r\n"
			+ "    \"amf\": \"A7B7\",\r\n"
			+ "    \"gnbIp\":\"10.244.0.11\",\r\n"
			+ "    \"slice\":{\r\n"
			+ "        \"sst\": 1,\r\n"
			+ "        \"sd\": \"010000\"\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static String CREATE_UE_JSON_STRING_FOR_WEB_BUSINESS = "{\r\n"
			+ "  \"ueId\" : \"imsi-001350123456333\",\r\n"
			+ "  \"plmnID\" : \"00135\",\r\n"
			+ "  \"userNumber\" : 1,\r\n"
			+ "  \"AuthenticationSubscription\" : {\r\n"
			+ "    \"authenticationManagementField\" : \"A7B7\",\r\n"
			+ "    \"authenticationMethod\" : \"5G_AKA\",\r\n"
			+ "    \"op\" : \"FEDCBA9876543210FEDCBA9876543210\",\r\n"
			+ "    \"encPermanentKey\" : \"00112233445566778899AABBCCDDEEFF\",\r\n"
			+ "    \"sequenceNumber\" : {\r\n"
			+ "      \"sqnScheme\" : \"NON_TIME_BASED\",\r\n"
			+ "      \"sqn\" : \"0000000b9604\"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"AccessAndMobilitySubscriptionData\" : {\r\n"
			+ "    \"gpsis\" : [ \"\" ],\r\n"
			+ "    \"subscribedUeAmbr\" : {\r\n"
			+ "      \"uplink\" : \"2 Gbps\",\r\n"
			+ "      \"downlink\" : \"4 Gbps\"\r\n"
			+ "    },\r\n"
			+ "    \"nssai\" : {\r\n"
			+ "      \"defaultSingleNssais\" : [ {\r\n"
			+ "        \"sd\" : \"010000\",\r\n"
			+ "        \"sst\" : 1,\r\n"
			+ "        \"isDefault\" : true\r\n"
			+ "      }, {\r\n"
			+ "        \"sd\" : \"112233\",\r\n"
			+ "        \"sst\" : 1,\r\n"
			+ "        \"isDefault\" : true\r\n"
			+ "      } ],\r\n"
			+ "      \"singleNssais\" : [ ]\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"SmfSelectionSubscriptionData\" : {\r\n"
			+ "    \"subscribedSnssaiInfos\" : {\r\n"
			+ "      \"01010000\" : {\r\n"
			+ "        \"dnnInfos\" : [ {\r\n"
			+ "          \"dnn\" : \"internet\"\r\n"
			+ "        }, {\r\n"
			+ "          \"dnn\" : \"internet2\"\r\n"
			+ "        } ]\r\n"
			+ "      },\r\n"
			+ "      \"01112233\" : {\r\n"
			+ "        \"dnnInfos\" : [ {\r\n"
			+ "          \"dnn\" : \"internet\"\r\n"
			+ "        }, {\r\n"
			+ "          \"dnn\" : \"internet2\"\r\n"
			+ "        } ]\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"SessionManagementSubscriptionData\" : [ {\r\n"
			+ "    \"singleNssai\" : {\r\n"
			+ "      \"sd\" : \"010000\",\r\n"
			+ "      \"sst\" : 1,\r\n"
			+ "      \"isDefault\" : true\r\n"
			+ "    },\r\n"
			+ "    \"dnnConfigurations\" : {\r\n"
			+ "      \"internet\" : {\r\n"
			+ "        \"sscModes\" : {\r\n"
			+ "          \"defaultSscMode\" : \"SSC_MODE_1\",\r\n"
			+ "          \"allowedSscModes\" : [ \"SSC_MODE_2\", \"SSC_MODE_3\" ]\r\n"
			+ "        },\r\n"
			+ "        \"sessionAmbr\" : {\r\n"
			+ "          \"uplink\" : \"1 Gbps\",\r\n"
			+ "          \"downlink\" : \"2 Gbps\"\r\n"
			+ "        },\r\n"
			+ "        \"5gQosProfile\" : {\r\n"
			+ "          \"5qi\" : 9,\r\n"
			+ "          \"arp\" : {\r\n"
			+ "            \"preemptCap\" : \"NOT_PREEMPT\",\r\n"
			+ "            \"preemptVuln\" : \"PREEMPTABLE\",\r\n"
			+ "            \"priorityLevel\" : 8\r\n"
			+ "          }\r\n"
			+ "        },\r\n"
			+ "        \"pduSessionTypes\" : {\r\n"
			+ "          \"defaultSessionType\" : \"IPV4\",\r\n"
			+ "          \"allowedSessionTypes\" : [ \"IPV4\" ]\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"internet2\" : {\r\n"
			+ "        \"sscModes\" : {\r\n"
			+ "          \"defaultSscMode\" : \"SSC_MODE_1\",\r\n"
			+ "          \"allowedSscModes\" : [ \"SSC_MODE_2\", \"SSC_MODE_3\" ]\r\n"
			+ "        },\r\n"
			+ "        \"sessionAmbr\" : {\r\n"
			+ "          \"uplink\" : \"1 Gbps\",\r\n"
			+ "          \"downlink\" : \"2 Gbps\"\r\n"
			+ "        },\r\n"
			+ "        \"5gQosProfile\" : {\r\n"
			+ "          \"5qi\" : 9,\r\n"
			+ "          \"arp\" : {\r\n"
			+ "            \"preemptCap\" : \"NOT_PREEMPT\",\r\n"
			+ "            \"preemptVuln\" : \"PREEMPTABLE\",\r\n"
			+ "            \"priorityLevel\" : 8\r\n"
			+ "          }\r\n"
			+ "        },\r\n"
			+ "        \"pduSessionTypes\" : {\r\n"
			+ "          \"defaultSessionType\" : \"IPV4\",\r\n"
			+ "          \"allowedSessionTypes\" : [ \"IPV4\" ]\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  } ],\r\n"
			+ "  \"AmPolicyData\" : {\r\n"
			+ "    \"subscCats\" : [ \"saviah\" ]\r\n"
			+ "  },\r\n"
			+ "  \"SmPolicyData\" : {\r\n"
			+ "    \"smPolicySnssaiData\" : {\r\n"
			+ "      \"01010000\" : {\r\n"
			+ "        \"snssai\" : {\r\n"
			+ "          \"sd\" : \"010000\",\r\n"
			+ "          \"sst\" : 1,\r\n"
			+ "          \"isDefault\" : true\r\n"
			+ "        },\r\n"
			+ "        \"smPolicyDnnData\" : {\r\n"
			+ "          \"internet\" : {\r\n"
			+ "            \"dnn\" : \"internet\"\r\n"
			+ "          },\r\n"
			+ "          \"internet2\" : {\r\n"
			+ "            \"dnn\" : \"internet2\"\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"01112233\" : {\r\n"
			+ "        \"snssai\" : {\r\n"
			+ "          \"sd\" : \"010000\",\r\n"
			+ "          \"sst\" : 1,\r\n"
			+ "          \"isDefault\" : true\r\n"
			+ "        },\r\n"
			+ "        \"smPolicyDnnData\" : {\r\n"
			+ "          \"internet\" : {\r\n"
			+ "            \"dnn\" : \"internet\"\r\n"
			+ "          },\r\n"
			+ "          \"internet2\" : {\r\n"
			+ "            \"dnn\" : \"internet2\"\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"PccRules\" : [ ]\r\n"
			+ "}";

}
